// [name, cart, promoCodes, region?] — kind "gen" uses promos, "mod" uses modPromos
type C = { name: string; cart: { sku: string; qty: number }[]; codes?: string[]; eu?: boolean; free?: boolean };
export const gen: C[] = [
  { name: "single food line", cart: [{ sku: "apple", qty: 3 }] },
  { name: "merge duplicate skus keeps order", cart: [{ sku: "mug", qty: 1 }, { sku: "apple", qty: 2 }, { sku: "mug", qty: 2 }] },
  { name: "empty cart", cart: [] },
  { name: "unknown sku", cart: [{ sku: "nope", qty: 1 }] },
  { name: "qty zero", cart: [{ sku: "apple", qty: 0 }] },
  { name: "qty fractional", cart: [{ sku: "apple", qty: 1.5 }] },
  { name: "merged qty over 99", cart: [{ sku: "apple", qty: 60 }, { sku: "apple", qty: 40 }] },
  { name: "negative line merged to valid", cart: [{ sku: "apple", qty: 5 }, { sku: "apple", qty: -2 }] },
  { name: "unknown promo", cart: [{ sku: "apple", qty: 1 }], codes: ["NOPE"] },
  { name: "promo case-insensitive", cart: [{ sku: "mug", qty: 2 }], codes: ["save10"] },
  { name: "duplicate code counts once", cart: [{ sku: "mug", qty: 2 }], codes: ["SAVE10", "save10"] },
  { name: "two order-level promos conflict", cart: [{ sku: "mug", qty: 2 }], codes: ["SAVE10", "FIVEOFF"] },
  { name: "bogo + percent combine", cart: [{ sku: "apple", qty: 5 }, { sku: "mug", qty: 1 }], codes: ["APPLEBOGO", "SAVE10"] },
  { name: "bogo sku absent gives 0", cart: [{ sku: "mug", qty: 1 }], codes: ["APPLEBOGO"] },
  { name: "percent never touches digital", cart: [{ sku: "ebook", qty: 2 }, { sku: "mug", qty: 1 }], codes: ["SAVE10"] },
  { name: "min subtotal not met", cart: [{ sku: "mug", qty: 3 }], codes: ["BIG15"] },
  { name: "min subtotal measured after bogo on base", cart: [{ sku: "mug", qty: 4 }], codes: ["BIG15", "MUGBOGO"] },
  { name: "percent rounding half up", cart: [{ sku: "apple", qty: 1 }, { sku: "song", qty: 1 }], codes: ["SAVE10"], eu: true },
  { name: "fixed capped by base", cart: [{ sku: "apple", qty: 2 }, { sku: "ebook", qty: 3 }], codes: ["FIVEOFF"] },
  { name: "global cap reduces order-level", cart: [{ sku: "mug", qty: 2 }, { sku: "ebook", qty: 1 }], codes: ["MUGBOGO", "HUGE"] },
  { name: "digital-only no shipping", cart: [{ sku: "ebook", qty: 2 }, { sku: "song", qty: 3 }], codes: ["EBOGO"] },
  { name: "free shipping at exactly 5000", cart: [{ sku: "apple", qty: 40 }] },
  { name: "shipping just under threshold after discount", cart: [{ sku: "lamp", qty: 1 }, { sku: "apple", qty: 1 }], codes: ["SAVE10"] },
  { name: "weight surcharge ceil kg", cart: [{ sku: "lamp", qty: 1 }, { sku: "mug", qty: 1 }], codes: ["HUGE"] },
  { name: "split attribution food/general EU tax", cart: [{ sku: "coffee", qty: 2 }, { sku: "mug", qty: 1 }], codes: ["SAVE10"], eu: true },
  { name: "shipping taxed at general rate", cart: [{ sku: "mug", qty: 1 }], eu: true },
  { name: "free-ship: already free", cart: [{ sku: "lamp", qty: 2 }], free: true },
  { name: "free-ship: digital only", cart: [{ sku: "ebook", qty: 1 }], free: true },
  { name: "free-ship: counts discount", cart: [{ sku: "lamp", qty: 1 }], codes: ["SAVE10"], free: true },
  { name: "free-ship: bogo counts", cart: [{ sku: "mug", qty: 2 }, { sku: "ebook", qty: 5 }], codes: ["MUGBOGO"], free: true },
];
export const mod: C[] = [
  { name: "A: threshold 4000", cart: [{ sku: "apple", qty: 32 }] },
  { name: "A: just under 4000", cart: [{ sku: "apple", qty: 31 }] },
  { name: "A: order-level no longer counts", cart: [{ sku: "lamp", qty: 1 }], codes: ["SAVE10"] },
  { name: "A: bogo still counts", cart: [{ sku: "mug", qty: 3 }], codes: ["MUGBOGO"] },
  { name: "A: free-ship follows", cart: [{ sku: "mug", qty: 2 }], codes: ["FIVEOFF"], free: true },
  { name: "A: free-ship bogo", cart: [{ sku: "mug", qty: 3 }], codes: ["MUGBOGO"], free: true },
  { name: "B: category food", cart: [{ sku: "coffee", qty: 1 }, { sku: "mug", qty: 1 }], codes: ["FOOD20"], eu: true },
  { name: "B: category digital applies", cart: [{ sku: "ebook", qty: 1 }, { sku: "apple", qty: 1 }], codes: ["digi50"] },
  { name: "B: category after bogo", cart: [{ sku: "ebook", qty: 3 }], codes: ["EBOGO", "DIGI50"], eu: true },
  { name: "B: conflicts with percent", cart: [{ sku: "mug", qty: 1 }], codes: ["GEN33", "SAVE10"] },
  { name: "B: capped", cart: [{ sku: "mug", qty: 2 }, { sku: "song", qty: 1 }], codes: ["MUGBOGO", "GEN33"], eu: true },
  { name: "C: unknown ignored + applied codes", cart: [{ sku: "apple", qty: 4 }], codes: ["nope", "applebogo", "Save10", "APPLEBOGO"] },
  { name: "C: no codes → empty list", cart: [{ sku: "apple", qty: 1 }] },
  { name: "regression: percent split", cart: [{ sku: "coffee", qty: 2 }, { sku: "mug", qty: 1 }], codes: ["SAVE10"], eu: true },
  { name: "regression: invalid qty", cart: [{ sku: "mug", qty: 100 }] },
];
